# Generated by Django 2.2.6 on 2020-01-16 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerride',
            name='date',
        ),
        migrations.RemoveField(
            model_name='offerride',
            name='time',
        ),
        migrations.AddField(
            model_name='offerride',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
