# Generated by Django 2.2.6 on 2020-03-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200116_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerride',
            name='passenger1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='passenger2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='passenger3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='passenger4',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='passenger5',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='passenger6',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
