# Generated by Django 2.2.6 on 2019-12-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegecommute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offerride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('startingpoint', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('vacancy', models.IntegerField()),
            ],
        ),
    ]
