# Generated by Django 2.2.6 on 2019-12-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegecommute', '0002_offerride'),
    ]

    operations = [
        migrations.DeleteModel(
            name='offerride',
        ),
    ]
