# Generated by Django 2.2.6 on 2020-03-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegecommute', '0003_delete_offerride'),
    ]

    operations = [
        migrations.DeleteModel(
            name='commute',
        ),
    ]
